version: "3.1"

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: lizee
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: "Tx4BXPgfc]@;r"
    networks:
      testing_net:
        ipv4_address: 172.28.1.1
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  # Deploy server
  app:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    networks:
      testing_net:
        ipv4_address: 172.28.1.2
    depends_on:
      - db

# Create network bridge between docker instances
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16
